Update for React Native tvOS
mParticle/docs pull request #128
Opened 2022-07-18 13:17 UTC by BrandonStalnaker

## Summary
- Removed outdated code and added information for supporting react's tvOS repository

## Master Issue
- Closes https://mparticle-eng.atlassian.net/browse/SQDSDKS-4298

2022-07-18 14:10 UTC, rmi22186 commented on src/pages/developers/sdk/react-native/getting-started/index.md
> +For clients using the [react-native-tvos library](https://github.com/react-native-tvos/react-native-tvos) you will need to add the force flag to to the install code shown bellow. This allows the inst
```suggestion
For clients using the [react-native-tvos library](https://github.com/react-native-tvos/react-native-tvos) you will need to add the `force` flag to the install code as shown below. This tells the installer to ignore using the core react native repository and instead use the tvOS specific library instead.
```

2022-07-19 17:44 UTC, MystiBerry requested changes

2022-07-19 17:44 UTC, MystiBerry commented on src/pages/developers/sdk/react-native/getting-started/index.md
> +For clients using the [react-native-tvos library](https://github.com/react-native-tvos/react-native-tvos) you will need to add the `force` flag to the install code as shown below. This tells the inst
```suggestion
For clients using the [react-native-tvos library](https://github.com/react-native-tvos/react-native-tvos) you must add the `force` flag to the install code as shown below. This tells the installer to ignore using the core React Native repository and instead use the tvOS-specific library instead.
```

2022-07-19 18:10 UTC, MystiBerry approved these changes

2022-07-20 14:03 UTC, merged