Add Examples of summary events
mParticle/docs pull request #129
Opened 2022-07-18 13:59 UTC by BrandonStalnaker

## Summary
- Add examples of summary events for Roku

## Master Issue
- Closes https://mparticle-eng.atlassian.net/browse/SQDSDKS-4298

2022-07-18 14:08 UTC, alexs-mparticle requested changes

2022-07-18 14:08 UTC, alexs-mparticle commented on src/pages/developers/sdk/roku/media/index.md
> +Once your session is instantiated, you will need to trigger a `SessionStart`. This should be done at the moment the user interacts with your content. For example, if the media is set to trigger on a
I think this should be bolded for emphasis.

```suggestion
Once your session is instantiated, you will need to trigger a `SessionStart`. This should be done at the moment the user interacts with your content. For example, if the media is set to trigger on a user click, and your player fires a `play` event when the content starts, the session must begin before the `play` event. Every method accepts the `MediaSession` and an optional `customAttributes` object. **The mParticle Roku SDK DOES NOT track and update the session object for you.** If your are missing data downstream be sure are add it here in the session object first.
```

2022-07-18 14:57 UTC, BrandonStalnaker commented on src/pages/developers/sdk/roku/media/index.md
> +Once your session is instantiated, you will need to trigger a `SessionStart`. This should be done at the moment the user interacts with your content. For example, if the media is set to trigger on a
```suggestion
Once your session is instantiated, you will need to trigger a `SessionStart`. This should be done at the moment the user interacts with your content. For example, if the media is set to trigger on a user click, and your player fires a `play` event when the content starts, the session must begin before the `play` event. Every method accepts the `MediaSession` and an optional `customAttributes` object. **The mParticle Roku SDK DOES NOT track and update the session object for you.** If your are missing data downstream be sure you are setting it here in the session object first.
```

2022-07-19 17:34 UTC, peterjenkins approved these changes
Left minor suggested change but otherwise looks good.

2022-07-19 17:34 UTC, peterjenkins commented on src/pages/developers/sdk/roku/media/index.md
> +Once your session is instantiated, you will need to trigger a `SessionStart`. This should be done at the moment the user interacts with your content. For example, if the media is set to trigger on a
```suggestion
Once your session is instantiated, you will need to trigger a `SessionStart`. This should be done at the moment the user interacts with your content. For example, if the media is set to trigger on a user click, and your player fires a `play` event when the content starts, the session must begin before the `play` event. Every method accepts the `MediaSession` and an optional `customAttributes` object. **The mParticle Roku SDK DOES NOT track and update the session object for you.** If you are missing data downstream, be sure you are setting it here in the session object first.
```

2022-07-19 17:40 UTC, MystiBerry approved these changes
Approved with Peter's correction of "your" to "you are"

2022-07-19 17:52 UTC, alexs-mparticle approved these changes

2022-07-19 17:54 UTC, merged