Apptentive doc updates
mParticle/docs pull request #66
Opened 2021-01-29 22:07 UTC by melj32app

Refresh product capabilities and provide further details.

# Summary

(Please provide a high level summary)

2021-01-29 22:11 UTC, melj32app commented
@cla-bot check

2021-01-29 22:21 UTC, samdozor requested changes

2021-01-29 22:21 UTC, samdozor commented on src/pages/integrations/apptentive/event/index.md
> +In order to enable mParticle’s integration with Apptentive, you will need your Apptentive App Key and Apptentive App Signature for each respective app and environment which you can get from Apptentiv
```suggestion
In order to enable mParticle's integration with Apptentive, you will need your Apptentive App Key and Apptentive App Signature for each respective app and environment which you can get from Apptentive's [API and Development](https://be.apptentive.com/apps/current/settings/api) page. If you need assistance to get an account, you can contact your Apptentive representative or reach out [here](mailto:support@apptentive.com).
```

2021-01-29 22:21 UTC, samdozor commented on src/pages/integrations/apptentive/event/index.md
>      compile ('com.mparticle:android-apptentive-kit:4.+')
```suggestion
    compile ('com.mparticle:android-apptentive-kit:5.+')
```

2021-01-29 22:22 UTC, samdozor commented
@melj32app thank you so much for the PR. Looks great. I made two small tweaks but otherwise this looks good. Can you go ahead and sign the cla per the note above? then we'll get this merged.

2021-01-29 22:29 UTC, melj32app commented
@samdozor I believe it is saying that you aren't cla-signed as I did the cla check and comment.

2021-01-29 23:12 UTC, melj32app commented
@cla-bot check

2021-02-02 20:03 UTC, samdozor approved these changes

2021-02-02 20:03 UTC, merged